### ISSUE TITLE
Embeded Tableau sheet won't update on url change

### ISSUE THREAD

**Issue by PurpleMonkeyWrench** [coopermaruyama/tableau-react#15]
I am trying to embed Tableau worksheets into my ReactJS application. I have a menu with a list of report names (in react) and when the menu item is clicked, it updates state which contains the report name. I decided to use the tableau-react npm package to complete this task.

When I first click on a menu item, it properly embeds the tableau report onto the page. When I click on another menu item (updating the state which is feeding the url) the tableau report refreshed, but continues to show the first report as if the url did not change. If I then click on a third menu item, the embed tableau report will refresh again, but this time it will show the second report item I clicked. Every subsequent menu item click refreshes the embed tableau report to the previous item clicked.

I am controlling state using Redux and in the Redux Dev Tools I've determined that everything with state is running correctly. Every menu item click properly updates state. I also put a console.log on the url that is being passed to the TableauReport url attribute, and that is correct also.

```
const Reports = props => {
  const { reportUrl } = props;
  return (
    reportUrl && <TableauReport url={reportUrl} />
  );
};
```
```
Menu Item Click       Tableau Report Shown
null                           null
Report 1                   Report 1
Report 2                   Report 1
Report 3                   Report 2
Report 4                   Report 3
Report 5                   Report 4
```

**Comment by coopermaruyama** [comment]
Hi, thanks for the detailed report. Unfortunately I no longer maintain this, mainly because I don’t have access to a proper tableau account anymore and have not worked with tableau in years. But I’ll try to help nonetheless. 

First, can you check that the url is changing when going from `Report 1` => `Report 2`? and post the url for each one here?

The thing that “triggers” the changing is here: https://github.com/coopermaruyama/tableau-react/blob/master/src/TableauReport.jsx#L48

I would try putting a breakpoint there and see if it’s calling that function the first time you go from report 1 => report 2.

Also, if I remember correctly, tableau has some kind of token that they return for each URL, and that token can only be used once. If you try to use the same token again, it might cause this kind of behavior. I would check that as well.

**Comment by PurpleMonkeyWrench** [comment]
This for the feedback!

Yes when first going from Report 1 => Report 2 the `isReportChanged` trigger is correctly set:

![image](https://user-images.githubusercontent.com/17533208/62385141-42752600-b522-11e9-9412-74228ec0acf0.png)

`nextProps.url` is also displaying the correct URL.  However, when it calls `this.initTableau()` (because isReportChanged is true) inside the `getUrl() `function it uses `this.props.url`, which is still pointed to the previous url, not the new one.

![image](https://user-images.githubusercontent.com/17533208/62385872-39855400-b524-11e9-89fe-dbdc23799cb2.png)

That seems to be why it is always showing the previous url instead of the new one.

**Comment by PurpleMonkeyWrench** [comment]
I believe I found the issue and created a pull request to resolve it:  [Pull Request](https://github.com/coopermaruyama/tableau-react/pull/16)

The check to see if the URL changed does not pass the `nextProps.url` to the `getUrl()` function, it passes the current props.  I updated the code to use the `nextUrl` if it exists.

**Comment by coopermaruyama** [comment]
PR is merged and new version is published to npm. Thanks!
